### ISSUE TITLE
Doesn't respect tsconfig.json

### ISSUE THREAD

**Issue by azz** [azz/jest-runner-tsc#2]
I thought the TS Compiler API would do it by default, but looks like I need to make changes to support tsconfig options.

**Comment by jasonkuhrt** [comment]
I did a bit of digging and found https://github.com/Microsoft/TypeScript/issues/5276. Its a bit old but maybe still valid (some recent comments).

**Comment by jasonkuhrt** [comment]
Tried playing with a fix tonight. I noted that reading my tsconfig.json file wasn't allowing my test suite to finish at all. I started inlining the options again to remove one by one. It seems that `lib` is causing issues in a jest context? No idea really yet. Computer fans start blaring and tests never finish. If I remove `lib` option of course some relying on it start failing but the test suite will actually run to completion rather than hanging.

```js
    const program = ts.createProgram([testPath], {
      noEmit: true,
      strict: true,
      noImplicitReturns: true,
      esModuleInterop: true,
      target: 'es5',
      module: 'commonjs',
      outDir: './build',
      declaration: true,
      sourceMap: true,
      lib: ['DOM', 'ES5', 'ScriptHost', 'ES2015.Promise'],
    });

```

**Comment by kwelch** [comment]
Not sure if this will help but [here is an example](https://github.com/jest-community/jest-runner-eslint/blob/master/src/runESLint.js#L70-L72) from `jest-runner-eslint`. From what I can tell though it looks as though you used this as inspiration.
